version: '3.4'

services:
  pastebinasp:
    # image: pastebin:v1
    image: ${DOCKER_REGISTRY-}pastebinasp
    build:
      context: .
      dockerfile: PasteBinASP/Dockerfile
    ports:
      - "80"
      - "44392"
    networks:
      - appnet
    depends_on:
      - postgres

  postgres:
    image: postgres:12.16-bullseye
    hostname: "PastebinPostgresDatabase"
    container_name: "PostgresDatabase"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Pastebin
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - appnet

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.crt:/etc/nginx/cert.crt:ro
      - ./nginx/cert.rsa:/etc/nginx/cert.rsa:ro
    ports:
      - "5001:44392"
    networks:
      - internet
      - appnet
    depends_on:
      - pastebinasp

  minio:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z.fips
    command: server /data/minio --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: PastebinMinIO
    volumes:
      - ./docker-volumes/minio:/data/minio
    networks:
      - appnet

  redis:
    image: redis:alpine3.18
    hostname: "PastebinRedisCache"
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/redis:/data
    networks:
      - appnet

networks:
  internet:
    driver: bridge
    name: internet
  appnet:
    driver: bridge
    name: appnet