// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasteBinASP.DbContexts;

#nullable disable

namespace PasteBinASP.Migrations
{
    [DbContext(typeof(PastebinDbContext))]
    [Migration("20231112045958_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("short_link_id_sequence")
                .HasMin(1L)
                .HasMax(2147483647L);

            modelBuilder.Entity("PasteBinASP.Entities.ShortLink", b =>
                {
                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_date_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RequestsCount")
                        .HasColumnType("integer")
                        .HasColumnName("requests_count");

                    b.HasKey("Link")
                        .HasName("pk_short_links");

                    b.ToTable("short_links", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
